name: Build docker image

on:
  push:
    branches:
    - master
    - 4.x

    tags:
    - '*'

  pull_request:

jobs:
  php74:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: 7.4
        tags: 7.4,7,latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 7
  php73:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: 7.3
        tags: 7.3
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 7
  php72:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: 7.2
        tags: 7.2
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 7
  ### dev
  php74-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: 7.4
        dev: 1
        tags: 7.4-dev,7-dev,dev
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 7
  php73-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: 7.3
        dev: 1
        tags: 7.3-dev
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 7
  php72-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: 7.2
        dev: 1
        tags: 7.2-dev
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 7
  ### dev-macos
  php74-dev-macos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: 7.4
        dev_macos: 1
        tags: 7.4-dev-macos,7-dev-macos,dev-macos
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 7
  php73-dev-macos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: 7.3
        dev_macos: 1
        tags: 7.3-dev-macos
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 7
  php72-dev-macos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: 7.2
        dev_macos: 1
        tags: 7.2-dev-macos
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 7
