name: Build docker image

on:
  push:
    branches:
    - master
    - 4.x

    tags:
    - '*'

  pull_request:

env:
  BASE_IMAGE_STABILITY_TAG: 4.35.7
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  php82:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '8.2'
        tags: 8.2,8,latest
        platform: linux/amd64,linux/arm64
  php81:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '8.1'
        tags: 8.1
        platform: linux/amd64,linux/arm64
  php80:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '8.0'
        tags: '8.0'
        platform: linux/amd64,linux/arm64
  ### dev
  php82-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '8.2'
        dev: 1
        tags: 8.2-dev,8-dev,dev
        platform: linux/amd64,linux/arm64
  php81-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '8.1'
        dev: 1
        tags: 8.1-dev
        platform: linux/amd64,linux/arm64
  php80-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '8.0'
        dev: 1
        tags: 8.0-dev
        platform: linux/amd64,linux/arm64
  ### dev-macos
  php82-dev-macos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '8.2'
        dev_macos: 1
        tags: 8.2-dev-macos,8-dev-macos,dev-macos
        platform: linux/amd64,linux/arm64
  php81-dev-macos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '8.1'
        dev_macos: 1
        tags: 8.1-dev-macos
        platform: linux/amd64,linux/arm64
  php80-dev-macos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '8.0'
        dev_macos: 1
        tags: 8.0-dev-macos
        platform: linux/amd64,linux/arm64
