name: Build docker image

on:
  push:
    branches:
    - master
    - 4.x

    tags:
    - '*'

  pull_request:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  WODBY1_REGISTRY_USERNAME: ${{ secrets.WODBY1_REGISTRY_USERNAME }}
  WODBY1_REGISTRY_PASSWORD: ${{ secrets.WODBY1_REGISTRY_PASSWORD }}

jobs:
  php81:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '8.1'
        tags: 8.1,8,latest
        platform: linux/amd64,linux/arm64
  php80:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '8.0'
        tags: '8.0'
        platform: linux/amd64,linux/arm64
  php74:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '7.4'
        tags: 7.4,7
        platform: linux/amd64,linux/arm64
  php73:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '7.3'
        tags: '7.3'
        platform: linux/amd64,linux/arm64
  ### dev
  php81-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '8.1'
        dev: 1
        tags: 8.1-dev,8-dev,dev
        platform: linux/amd64,linux/arm64
  php80-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '8.0'
        dev: 1
        tags: 8.0-dev
        platform: linux/amd64,linux/arm64
  php74-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '7.4'
        dev: 1
        tags: 7.4-dev,7-dev
        platform: linux/amd64,linux/arm64
  php73-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '7.3'
        dev: 1
        tags: 7.3-dev
        platform: linux/amd64,linux/arm64
  ### dev-macos
  php81-dev-macos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '8.1'
        dev_macos: 1
        tags: 8.1-dev-macos,8-dev-macos,dev-macos
        platform: linux/amd64,linux/arm64
  php80-dev-macos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '8.0'
        dev_macos: 1
        tags: 8.0-dev-macos
        platform: linux/amd64,linux/arm64
  php74-dev-macos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '7.4'
        dev_macos: 1
        tags: 7.4-dev-macos,7-dev-macos
        platform: linux/amd64,linux/arm64
  php73-dev-macos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '7.3'
        dev_macos: 1
        tags: 7.3-dev-macos
        platform: linux/amd64,linux/arm64
